import { contentProps } from "./types";

export const dummyUserData = [
  {
    id: 1,
    username: "test",
    email: "test@gmail",
    password: "password1",
    user_role: "user",
  },
  {
    id: 2,
    username: "test2",
    email: "test2@gmail",
    password: "password2",
    user_role: "user",
  },
  {
    id: 3,
    username: "test3",
    email: "test3@gmail",
    password: "password3",
    user_role: "user",
  },
  {
    id: 4,
    username: "test4",
    email: "test4@gmail",
    password: "password4",
    user_role: "user",
  },
];

export const dummyContentData: contentProps[] = [
  {
    id: 1,
    title: "Cara menyambut Dunia",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum",
    tags: ["#hello", "#world"],
    images: [
      "/dummyimglandscape.jpg",
      "/dummyimglandscape.jpg",
      "/dummyimgportrait.jpg",
    ],
    date: "2022-01-01",
  },
  {
    id: 2,
    title: "Cara tidur",
    body: "Get tired first",
    tags: ["#internet of things", "#tired", "#sleep", "#test"],
    images: [
      "https://picsum.photos/200/300",
      "/dummyimgportrait.jpg",
      "/dummyimglandscape.jpg",
      "/dummyimglandscape.jpg",
    ],
    date: "2022-01-01",
  },
  {
    id: 4,
    title: "Cara menyalakan handphone",
    body: "press power button !",
    images: ["/Anime Suite Ocean.jpg"],
    date: "2022-01-01",
  },
  {
    id: 5,
    title: "Cara menyalakan handphone",
    body: "press power button !",
    images: ["/AplhaCW.jpg"],
    date: "2022-01-01",
  },
  {
    id: 6,
    title: "Cara menyalakan handphone",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 7,
    title: "Cara menyalakan handphone",
    body: "press power button !",
    images: ["Eva-01Berserk.png"],
    date: "2022-01-01",
  },
  {
    id: 8,
    title: "Cara menyalakan handphone",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 9,
    title: "Cara asjdhasjkhdjsjahdjsa",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 10,
    title: "iasjdiosajdoisajoidsajdosj",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 11,
    title: "hello ceng",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 12,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 13,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 14,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 15,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 16,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 17,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 21312,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 12312,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 2323,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 5162,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 71721,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 21721,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 721,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 7172172,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 24124,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 125215,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 54754,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 76976,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 757,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 32532,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 32532532,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 547645645,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 7547,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 421412,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 6756568,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 12464757,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
  {
    id: 12352535754,
    title: "tuang ",
    body: "press power button !",
    images: ["https://picsum.photos/200/300"],
    date: "2022-01-01",
  },
];
