###
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "username":"tests2",
    "email":"tests2@gmail.com",
    "password":"password",
    "confPassword":"password"
}
###
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"password"
}


